title:              My Blog
email:              choiwh1008@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             pulnip
baseurl:            "/"
url:                "https://pulnip.github.io/MyWebSite1/"

lang: ko
timezone: Asia/Seoul

# Social Profiles
twitter_username:
github_username:    pulnip
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
